# Generated by Django 2.1.2 on 2019-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creater',
            fields=[
                ('adminemail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('admilpass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHERS')], max_length=20)),
                ('contact_no', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('skils', models.CharField(max_length=80)),
                ('experience', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Negative_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('correct_ans', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Non_Negative_Eaxm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('correct_ans', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHERS')], max_length=20)),
                ('contact_no', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('java', 'JAVA'), ('python', 'PYTHON'), ('sql', 'SQL')], max_length=80)),
                ('experience', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
